---
- name: Log Ollama start status
  debug:
    msg: |
      Ollama service has been started successfully.
      API is now available at http://localhost:11434
  when: ollama_verify is defined and ollama_verify.status == 200

- name: Log Ollama start failure
  debug:
    msg: |
      [WARNING] Failed to start Ollama service.
      Please check the service logs: journalctl -u ollama -n 50
  when: ollama_verify is defined and ollama_verify.status != 200
  failed_when: true
